steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "$_IMAGE_NAME:latest"
      - .
      - "-f"
      - $_DOCKERFILE_NAME
    dir: $_DOCKERFILE_DIR
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_IMAGE_NAME:latest"
    id: Push
images:
  - "$_IMAGE_NAME:latest"
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _K8S_YAML_PATH: kubernetes/definition.yaml
  _K8S_APP_NAME: server
  _GKE_CLUSTER: benchmarking-cluster-4
  _IMAGE_NAME: gcr.io/tfg-ivo/github.com/ivosequeros/gaze
  _DOCKERFILE_NAME: Dockerfile
  _K8S_NAMESPACE: default
  _DOCKERFILE_DIR: ""
  _K8S_ANNOTATIONS: gcb-trigger-id=57c13d10-96f4-4b8d-980c-f10309e69c1b
  _K8S_LABELS: ""
  _OUTPUT_BUCKET_PATH: tfg-ivo_cloudbuild/deploy
  _GKE_LOCATION: europe-west3-b
tags:
  - gcp-cloud-build-deploy
  - $_K8S_APP_NAME
timeout: 25m
