apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
  namespace: default
spec:
  replicas: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - image: gcr.io/tfg-ivo/github.com/ivosequeros/gaze-client:f986b243986a839efeab5b5858ced77a84cd103f929beac2edcf8e5a1738a85c
          imagePullPolicy: IfNotPresent
          name: client-sha256-1
          env:
            - name: IP
              value: 10.0.18.214
      nodeSelector:
        node: client
