apiVersion: batch/v1
kind: Job
metadata:
  name: client
spec:
  parallelism: 10
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
        - name: client
          image: gcr.io/tfg-ivo/github.com/ivosequeros/gaze-client
          imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 10
