steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      - --destination=gcr.io/tfg-ivo/github.com/ivosequeros/gaze-server:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=240h
    dir: .
    id: Build server
    waitFor: ["-"]

  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      - --destination=gcr.io/tfg-ivo/github.com/ivosequeros/gaze-client:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=240h
      - --context=dir://client
    dir: client
    id: Build client
    waitFor: ["-"]

  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - prepare
      - "--filename=deploy/server.yaml"
      - "--image=gcr.io/tfg-ivo/github.com/ivosequeros/gaze-server:$COMMIT_SHA"
      - "--app=server"
      - "--version=$COMMIT_SHA"
      - "--namespace=default"
      - "--annotation=gcb-build-id=$BUILD_ID"
      - "--output=output/server"
    id: Prepare deploy for server

  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - prepare
      - "--filename=deploy/client.yaml"
      - "--image=gcr.io/tfg-ivo/github.com/ivosequeros/gaze-client:$COMMIT_SHA"
      - "--app=client"
      - "--version=$COMMIT_SHA"
      - "--namespace=default"
      - "--annotation=gcb-build-id=$BUILD_ID"
      - "--output=output/client"
    id: Prepare deploy for client

  - name: gcr.io/cloud-builders/gsutil
    args:
      - "-c"
      - |-
        gsutil cp -r output/server/suggested gs://tfg-ivo_cloudbuild/deploy/config/server/$BUILD_ID/suggested
        gsutil cp -r output/server/expanded gs://tfg-ivo_cloudbuild/deploy/config/server/$BUILD_ID/expanded
    id: Save configs for server
    entrypoint: sh

  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - apply
      - "--filename=output/server/expanded"
      - "--cluster=benchmarking-cluster-4"
      - "--location=europe-west3-b"
      - "--namespace=default"
    id: Apply deploy for server

  - name: gcr.io/cloud-builders/gsutil
    args:
      - "-c"
      - |-
        gsutil cp -r output/client/suggested gs://tfg-ivo_cloudbuild/deploy/config/client/$BUILD_ID/suggested
        gsutil cp -r output/client/expanded gs://tfg-ivo_cloudbuild/deploy/config/client/$BUILD_ID/expanded
    id: Save configs for client
    entrypoint: sh

  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - apply
      - "--filename=output/client/expanded"
      - "--cluster=benchmarking-cluster-4"
      - "--location=europe-west3-b"
      - "--namespace=default"
    id: Apply deploy for client

images:
  - "gcr.io/tfg-ivo/github.com/ivosequeros/gaze-server:$COMMIT_SHA"
  - "gcr.io/tfg-ivo/github.com/ivosequeros/gaze-client:$COMMIT_SHA"
tags:
  - gcp-cloud-build-deploy
  - server
timeout: 30m
