apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - image: gcr.io/tfg-ivo/github.com/ivosequeros/gaze
          imagePullPolicy: Always
          name: server-sha256-1
          ports:
            - containerPort: 6142
              protocol: TCP
          resources:
            requests:
              cpu: 1m
      nodeSelector:
        node: server
